import { 
  UserProfile, 
  ResearchGroup, 
  ResearchLine, 
  MeetingAttendance, 
  ActivityTask, 
  LineResource, 
  LogbookEntry, 
  PhotoRecord 
} from '../types';

export const INITIAL_USERS: UserProfile[] = [
  // Admin
  {
    uid: 'admin-01',
    name: 'Coordenação Regional SESI RN',
    email: 'admin@sesi.org.br',
    role: 'admin',
    unit: 'SESI SÃO GONÇALO DO AMARANTE',
    matricula: 'ADM-9901',
    phone: '(84) 3200-1000',
    areaOrGrade: 'Gestão Pedagógica & Inovação',
    createdAt: '2026-02-01T08:00:00Z',
  },
  // Professores Líderes
  {
    uid: 'teacher-sg',
    name: 'Prof. Dr. Carlos Eduardo Medeiros',
    email: 'carlos.medeiros@sesi.org.br',
    role: 'teacher',
    unit: 'SESI SÃO GONÇALO DO AMARANTE',
    matricula: 'PROF-4412',
    phone: '(84) 99123-4567',
    areaOrGrade: 'Engenharia & Robótica',
    createdAt: '2026-02-05T09:00:00Z',
  },
  {
    uid: 'teacher-macau',
    name: 'Profa. Dra. Juliana Albuquerque',
    email: 'juliana.albuquerque@sesi.org.br',
    role: 'teacher',
    unit: 'SESI MACAU',
    matricula: 'PROF-3321',
    phone: '(84) 98877-6655',
    areaOrGrade: 'Química & Sustentabilidade',
    createdAt: '2026-02-06T10:00:00Z',
  },
  {
    uid: 'teacher-mossoro',
    name: 'Prof. Me. Lucas Ferreira Costa',
    email: 'lucas.costa@sesi.org.br',
    role: 'teacher',
    unit: 'SESI MOSSORÓ',
    matricula: 'PROF-7789',
    phone: '(84) 99432-1122',
    areaOrGrade: 'Física & Inteligência Artificial',
    createdAt: '2026-02-07T11:00:00Z',
  },
  // Alunos - SESI São Gonçalo do Amarante (Linha 1)
  {
    uid: 'student-sg-01',
    name: 'Arthur Vinícius Silva',
    email: 'arthur.silva@aluno.sesi.org.br',
    role: 'student',
    unit: 'SESI SÃO GONÇALO DO AMARANTE',
    matricula: 'ALU-2026-01',
    phone: '(84) 99988-1111',
    areaOrGrade: '3ª Série do Ensino Médio - Turma A',
    createdAt: '2026-02-10T14:00:00Z',
  },
  {
    uid: 'student-sg-02',
    name: 'Beatriz Vasconcelos Ramos',
    email: 'beatriz.ramos@aluno.sesi.org.br',
    role: 'student',
    unit: 'SESI SÃO GONÇALO DO AMARANTE',
    matricula: 'ALU-2026-02',
    phone: '(84) 99988-2222',
    areaOrGrade: '2ª Série do Ensino Médio - Turma B',
    createdAt: '2026-02-10T14:05:00Z',
  },
  {
    uid: 'student-sg-03',
    name: 'Caio Felipe Meireles',
    email: 'caio.meireles@aluno.sesi.org.br',
    role: 'student',
    unit: 'SESI SÃO GONÇALO DO AMARANTE',
    matricula: 'ALU-2026-03',
    phone: '(84) 99988-3333',
    areaOrGrade: '3ª Série do Ensino Médio - Turma A',
    createdAt: '2026-02-10T14:10:00Z',
  },
  // Alunos - Linha 2
  {
    uid: 'student-sg-04',
    name: 'Daniela Fontes Moura',
    email: 'daniela.moura@aluno.sesi.org.br',
    role: 'student',
    unit: 'SESI SÃO GONÇALO DO AMARANTE',
    matricula: 'ALU-2026-04',
    phone: '(84) 99988-4444',
    areaOrGrade: '2ª Série do Ensino Médio - Turma A',
    createdAt: '2026-02-10T14:15:00Z',
  },
  {
    uid: 'student-sg-05',
    name: 'Enzo Gabriel Soares',
    email: 'enzo.soares@aluno.sesi.org.br',
    role: 'student',
    unit: 'SESI SÃO GONÇALO DO AMARANTE',
    matricula: 'ALU-2026-05',
    phone: '(84) 99988-5555',
    areaOrGrade: '1ª Série do Ensino Médio - Turma C',
    createdAt: '2026-02-10T14:20:00Z',
  },
  // Alunos - Macau
  {
    uid: 'student-macau-01',
    name: 'Fernanda Lima Nogueira',
    email: 'fernanda.nogueira@aluno.sesi.org.br',
    role: 'student',
    unit: 'SESI MACAU',
    matricula: 'ALU-2026-06',
    phone: '(84) 98765-4321',
    areaOrGrade: '3ª Série do Ensino Médio',
    createdAt: '2026-02-12T10:00:00Z',
  },
  // Alunos - Mossoró
  {
    uid: 'student-mossoro-01',
    name: 'Gabriel Bezerra Dantas',
    email: 'gabriel.dantas@aluno.sesi.org.br',
    role: 'student',
    unit: 'SESI MOSSORÓ',
    matricula: 'ALU-2026-07',
    phone: '(84) 98111-2233',
    areaOrGrade: '3ª Série do Ensino Médio - Técnico em Automação',
    createdAt: '2026-02-12T11:00:00Z',
  },
];

export const INITIAL_GROUPS: ResearchGroup[] = [
  {
    id: 'group-sg-01',
    title: 'GPROB - Grupo de Pesquisa em Robótica e Sistemas Inteligentes',
    description: 'Investigação e desenvolvimento de protótipos de automação, sensoriamento remoto e visão computacional aplicados à indústria e ao meio ambiente.',
    unit: 'SESI SÃO GONÇALO DO AMARANTE',
    leaderTeacherId: 'teacher-sg',
    leaderTeacherName: 'Prof. Dr. Carlos Eduardo Medeiros',
    createdAt: '2026-02-05T09:30:00Z',
  },
  {
    id: 'group-macau-01',
    title: 'NUPES - Núcleo de Pesquisa em Energias Renováveis e Meio Ambiente',
    description: 'Estudos de dessalinização solar, biopolímeros a partir de resíduos da carcinicultura e eficiência energética.',
    unit: 'SESI MACAU',
    leaderTeacherId: 'teacher-macau',
    leaderTeacherName: 'Profa. Dra. Juliana Albuquerque',
    createdAt: '2026-02-06T10:30:00Z',
  },
  {
    id: 'group-mossoro-01',
    title: 'LABIOT - Laboratório de Automação e IoT para o Semiárido',
    description: 'Desenvolvimento de sistemas embarcados de baixo custo para otimização de recursos hídricos na fruticultura irrigada.',
    unit: 'SESI MOSSORÓ',
    leaderTeacherId: 'teacher-mossoro',
    leaderTeacherName: 'Prof. Me. Lucas Ferreira Costa',
    createdAt: '2026-02-07T11:30:00Z',
  },
];

export const INITIAL_LINES: ResearchLine[] = [
  {
    id: 'line-sg-01',
    groupId: 'group-sg-01',
    lineNumber: 1,
    title: 'Monitoramento IoT de Parâmetros Ambientais em Ambientes Escolares',
    area: 'Engenharia e Ciências da Computação',
    description: 'Criação de estações de monitoramento de qualidade do ar (CO2, temperatura e umidade) com envio de alertas para dashboards em tempo real.',
    studentIds: ['student-sg-01', 'student-sg-02', 'student-sg-03'],
    studentNames: ['Arthur Vinícius Silva', 'Beatriz Vasconcelos Ramos', 'Caio Felipe Meireles'],
    createdAt: '2026-02-08T09:00:00Z',
  },
  {
    id: 'line-sg-02',
    groupId: 'group-sg-01',
    lineNumber: 2,
    title: 'Visão Computacional para Triagem Automatizada de Resíduos Plásticos',
    area: 'Inteligência Artificial e Sustentabilidade',
    description: 'Implementação de redes neurais convolucionais em Raspberry Pi para classificação de polímeros (PET, PEAD, PVC) em esteiras de reciclagem.',
    studentIds: ['student-sg-04', 'student-sg-05'],
    studentNames: ['Daniela Fontes Moura', 'Enzo Gabriel Soares'],
    createdAt: '2026-02-08T09:30:00Z',
  },
  {
    id: 'line-macau-01',
    groupId: 'group-macau-01',
    lineNumber: 1,
    title: 'Bioplásticos Obtidos da Quitosana de Carapaças de Camarão',
    area: 'Química e Biotecnologia',
    description: 'Síntese de filmes biodegradáveis a partir de rejeitos da indústria de frutos do mar da região salineira.',
    studentIds: ['student-macau-01'],
    studentNames: ['Fernanda Lima Nogueira'],
    createdAt: '2026-02-08T10:00:00Z',
  },
  {
    id: 'line-mossoro-01',
    groupId: 'group-mossoro-01',
    lineNumber: 1,
    title: 'Irrigação de Precisão com Redes de Sensores LoRaWAN',
    area: 'Agronomia Digital e Telecomunicações',
    description: 'Controle autônomo de gotejamento por análise de umidade do solo em plantios de melão no semiárido potiguar.',
    studentIds: ['student-mossoro-01'],
    studentNames: ['Gabriel Bezerra Dantas'],
    createdAt: '2026-02-08T11:00:00Z',
  }
];

export const INITIAL_MEETINGS: MeetingAttendance[] = [
  {
    id: 'meet-01',
    groupId: 'group-sg-01',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT de Parâmetros Ambientais',
    date: '2026-02-12',
    time: '14:00 - 16:00',
    title: 'Reunião de Alinhamento Metodológico e Calibração dos Sensores MQ-135',
    agenda: '1. Revisão do cronograma FEBRACE; 2. Teste prático do circuito ESP32 com display OLED; 3. Divisão dos tópicos do diário de bordo.',
    summary: 'Todos os membros participaram ativamente. Circuito montado na protoboard com sucesso. Próxima etapa será a calibração com gás de referência.',
    records: [
      { studentId: 'student-sg-01', studentName: 'Arthur Vinícius Silva', status: 'present', note: 'Responsável pela programação do microcontrolador' },
      { studentId: 'student-sg-02', studentName: 'Beatriz Vasconcelos Ramos', status: 'present', note: 'Apresentou a revisão bibliográfica das normas ABNT' },
      { studentId: 'student-sg-03', studentName: 'Caio Felipe Meireles', status: 'present', note: 'Responsável pela montagem do protótipo físico' }
    ],
    createdAt: '2026-02-12T16:30:00Z'
  },
  {
    id: 'meet-02',
    groupId: 'group-sg-01',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT de Parâmetros Ambientais',
    date: '2026-02-19',
    time: '14:00 - 16:00',
    title: 'Sessão de Coleta de Dados e Validação dos Logs',
    agenda: '1. Verificação da taxa de amostragem de dados via MQTT; 2. Análise de ruído no sinal analógico.',
    summary: 'A aluna Beatriz precisou se ausentar para consulta médica previamente justificada. Arthur e Caio realizaram o teste com êxito.',
    records: [
      { studentId: 'student-sg-01', studentName: 'Arthur Vinícius Silva', status: 'present' },
      { studentId: 'student-sg-02', studentName: 'Beatriz Vasconcelos Ramos', status: 'absent_justified', note: 'Atestado médico entregue à coordenação' },
      { studentId: 'student-sg-03', studentName: 'Caio Felipe Meireles', status: 'present' }
    ],
    createdAt: '2026-02-19T16:30:00Z'
  }
];

export const INITIAL_TASKS: ActivityTask[] = [
  {
    id: 'task-01',
    groupId: 'group-sg-01',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    targetStudentId: 'student-sg-01',
    targetStudentName: 'Arthur Vinícius Silva',
    title: 'Desenvolver script em C++ / Arduino para leitura periódica do MQ-135 e DHT22',
    description: 'Implementar a biblioteca de leitura, configurar a taxa de envio a cada 10 segundos e formatar o payload JSON.',
    dueDate: '2026-02-25',
    priority: 'high',
    status: 'in_progress',
    teacherFeedback: 'Excelente início! Lembre-se de adicionar tratamento de erro caso o sensor DHT retorne NaN.',
    createdAt: '2026-02-13T09:00:00Z'
  },
  {
    id: 'task-02',
    groupId: 'group-sg-01',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    targetStudentId: 'student-sg-02',
    targetStudentName: 'Beatriz Vasconcelos Ramos',
    title: 'Estruturar a Introdução e Justificativa no padrão ABNT / Feira Científica',
    description: 'Escrever no mínimo 3 laudas com referencial teórico sobre qualidade do ar em salas de aula e impacto no rendimento acadêmico.',
    dueDate: '2026-02-28',
    priority: 'medium',
    status: 'completed',
    submissionLink: 'https://docs.google.com/document/d/sesi-artigo-revisao-qualidade-ar',
    submissionNotes: 'Documento finalizado com 12 referências de periódicos Scielo e IEEE.',
    teacherFeedback: 'Trabalho impecável na fundamentação teórica!',
    createdAt: '2026-02-13T09:15:00Z'
  },
  {
    id: 'task-03',
    groupId: 'group-sg-01',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    title: 'Projetar case em 3D (CAD/Fusion 360) para acondicionamento da placa no laboratório',
    description: 'Considerar aberturas para ventilação natural dos sensores e encaixe para display OLED 0.96".',
    dueDate: '2026-03-05',
    priority: 'low',
    status: 'pending',
    createdAt: '2026-02-15T10:00:00Z'
  }
];

export const INITIAL_RESOURCES: LineResource[] = [
  {
    id: 'res-01',
    groupId: 'group-sg-01',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    type: 'link',
    title: 'Repositório de Firmware e Bibliotecas no GitHub',
    url: 'https://github.com/sesi-icp/iot-air-quality-station',
    description: 'Código base com bibliotecas para ESP32, PubSubClient e Adafruit_Sensor.',
    uploadedBy: 'teacher-sg',
    uploadedByName: 'Prof. Dr. Carlos Eduardo Medeiros',
    createdAt: '2026-02-10T11:00:00Z'
  },
  {
    id: 'res-02',
    groupId: 'group-sg-01',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    type: 'file',
    title: 'Guia de Calibração de Sensores Eletroquímicos de Gás (PDF)',
    url: '#',
    fileName: 'Manual_Calibracao_Sensores_MQ_IEEE.pdf',
    fileSize: '2.4 MB',
    fileType: 'application/pdf',
    description: 'Documento técnico oficial para cálculo de Ro/Rs e curvas características.',
    uploadedBy: 'teacher-sg',
    uploadedByName: 'Prof. Dr. Carlos Eduardo Medeiros',
    createdAt: '2026-02-11T14:30:00Z'
  },
  {
    id: 'res-03',
    groupId: 'group-sg-01',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    type: 'link',
    title: 'Planilha de Registro de Dados de Bancada (Google Sheets)',
    url: 'https://docs.google.com/spreadsheets/d/sesi-icp-bancada-logs',
    description: 'Template oficial para preenchimento de leituras de temperatura e CO2 a cada 30 minutos.',
    uploadedBy: 'teacher-sg',
    uploadedByName: 'Prof. Dr. Carlos Eduardo Medeiros',
    createdAt: '2026-02-12T08:00:00Z'
  }
];

export const INITIAL_LOGBOOKS: LogbookEntry[] = [
  {
    id: 'log-01',
    studentId: 'student-sg-01',
    studentName: 'Arthur Vinícius Silva',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT de Parâmetros Ambientais',
    groupId: 'group-sg-01',
    date: '2026-02-14',
    hoursWorked: 3.5,
    stage: 'Metodologia e Prototipagem',
    objectives: 'Montar a primeira versão do circuito na protoboard e testar comunicação I2C com o display OLED 128x64.',
    methodology: 'Utilizamos uma placa ESP32 DevKit V1, conectando os pinos SDA (GPIO 21) e SCL (GPIO 22). Foi utilizado o software Arduino IDE 2.3 com a biblioteca U8g2.',
    activities: '1. Ligação física dos fios jumper;\n2. Scanner I2C para localizar o endereço do display (encontrado em 0x3C);\n3. Renderização de tela de boas-vindas com a logo do SESI ICP.',
    results: 'Display inicializou perfeitamente, taxa de atualização de 30 FPS sem flickering. Tensão de alimentação estável em 3.3V.',
    difficulties: 'Inicialmente o display não respondia devido a um cabo jumper partido, identificado após teste de continuidade no multímetro.',
    nextSteps: 'Integrar o sensor de gás MQ-135 na entrada analógica ADC1_CH0 (GPIO 36).',
    supervisorStatus: 'approved',
    supervisorComment: 'Excelente rigor no registro do problema e da solução com o multímetro! Parabéns pelo detalhamento técnico.',
    supervisorReviewedAt: '2026-02-15T10:00:00Z',
    createdAt: '2026-02-14T17:30:00Z'
  },
  {
    id: 'log-02',
    studentId: 'student-sg-02',
    studentName: 'Beatriz Vasconcelos Ramos',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT de Parâmetros Ambientais',
    groupId: 'group-sg-01',
    date: '2026-02-16',
    hoursWorked: 4.0,
    stage: 'Revisão Bibliográfica',
    objectives: 'Mapear estudos recentes (2021-2025) sobre limites recomendados de CO2 pela OMS e ANVISA em ambientes escolares.',
    methodology: 'Busca sistemática no Google Scholar e Scielo com as palavras-chave "qualidade do ar", "escolas", "dióxido de carbono" e "aprendizagem".',
    activities: 'Leitura de 8 artigos científicos, compilação de tabela comparativa de concentrações (PPM) e impactos na sonolência e foco de estudantes.',
    results: 'Verificou-se que concentrações acima de 1000 ppm já causam redução de até 15% na capacidade de concentração dos alunos.',
    difficulties: 'Alguns artigos internacionais na ScienceDirect estavam em acesso fechado, necessitando uso do portal de periódicos CAPES.',
    nextSteps: 'Redigir a subseção 2.1 do artigo científico do grupo com os dados tabulados.',
    supervisorStatus: 'approved',
    supervisorComment: 'Ótima fundamentação. Esses dados servirão como justificativa sólida para a relevância social da pesquisa.',
    supervisorReviewedAt: '2026-02-17T09:15:00Z',
    createdAt: '2026-02-16T18:00:00Z'
  },
  {
    id: 'log-03',
    studentId: 'student-sg-03',
    studentName: 'Caio Felipe Meireles',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT de Parâmetros Ambientais',
    groupId: 'group-sg-01',
    date: '2026-02-18',
    hoursWorked: 3.0,
    stage: 'Experimentação e Coleta de Dados',
    objectives: 'Submeter o protótipo montado a variações térmicas controladas em câmara de teste.',
    methodology: 'Colocação do circuito em recipiente fechado com fonte de calor controlada por termostato, registrando variação a cada 2 minutos.',
    activities: 'Aquecimento gradual de 24°C até 42°C, observando deriva térmica nas leituras do sensor analógico.',
    results: 'Foi detectado desvio linear de aproximadamente 1.8% a cada 5°C de elevação na temperatura.',
    difficulties: 'Necessidade de isolar os cabos para não derreter a fita isolante durante a medição máxima.',
    nextSteps: 'Implementar fórmula de compensação de temperatura no algoritmo do microcontrolador.',
    supervisorStatus: 'pending',
    createdAt: '2026-02-18T16:45:00Z'
  }
];

export const INITIAL_PHOTOS: PhotoRecord[] = [
  {
    id: 'photo-01',
    studentId: 'student-sg-01',
    studentName: 'Arthur Vinícius Silva',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    groupId: 'group-sg-01',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    caption: 'Montagem inicial da protoboard com ESP32 e display OLED no laboratório Maker do SESI São Gonçalo do Amarante.',
    date: '2026-02-14',
    stage: 'Metodologia e Prototipagem',
    tags: ['ESP32', 'Protoboard', 'Laboratório Maker', 'Bancada'],
    createdAt: '2026-02-14T17:40:00Z'
  },
  {
    id: 'photo-02',
    studentId: 'student-sg-03',
    studentName: 'Caio Felipe Meireles',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    groupId: 'group-sg-01',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1000&q=80',
    caption: 'Teste de calibração do sensor MQ-135 com auxílio do osciloscópio e fonte de bancada ajustável.',
    date: '2026-02-18',
    stage: 'Experimentação e Coleta de Dados',
    tags: ['Calibração', 'Instrumentação', 'Medição', 'Eletrônica'],
    createdAt: '2026-02-18T16:50:00Z'
  },
  {
    id: 'photo-03',
    studentId: 'student-sg-02',
    studentName: 'Beatriz Vasconcelos Ramos',
    lineId: 'line-sg-01',
    lineTitle: 'Monitoramento IoT',
    groupId: 'group-sg-01',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1000&q=80',
    caption: 'Reunião semanal com o orientador Prof. Carlos para discussão dos resultados obtidos na primeira rodada de testes.',
    date: '2026-02-12',
    stage: 'Revisão Bibliográfica',
    tags: ['Orientação', 'Equipe', 'SESI RN', 'Pesquisa Científica'],
    createdAt: '2026-02-12T16:45:00Z'
  }
];
